// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBad89bzJSNUhB5ynMUds8BokejP2QiGM4',
    appId: '1:1073439472535:web:061e579e9018edab71e2d2',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    authDomain: 'wosapp-a2214.firebaseapp.com',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    measurementId: 'G-QB04FM108G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCazxuu1WN9sOsjEroT2-RacAViGYHaH1g',
    appId: '1:1073439472535:android:50c52eda78611b5b71e2d2',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6SeaSYe7Wo_MiF7PQkb7Pr1zk3C-S5A',
    appId: '1:1073439472535:ios:ea04ec7eb191f99171e2d2',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    iosBundleId: 'com.example.wosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6SeaSYe7Wo_MiF7PQkb7Pr1zk3C-S5A',
    appId: '1:1073439472535:ios:ea04ec7eb191f99171e2d2',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    iosBundleId: 'com.example.wosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBad89bzJSNUhB5ynMUds8BokejP2QiGM4',
    appId: '1:1073439472535:web:197345b0d8bc805c71e2d2',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    authDomain: 'wosapp-a2214.firebaseapp.com',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    measurementId: 'G-DMF4HG0FLW',
  );
}
