// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  await dotenv.load(fileName: "firebase.env");
}

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["webapiKey"] ?? '',
    appId: dotenv.env["webappId"] ?? '',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    authDomain: 'wosapp-a2214.firebaseapp.com',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    measurementId: 'G-QB04FM108G',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["androidapiKey"] ?? '',
    appId: dotenv.env["androidappId"] ?? '',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["iosapiKey"] ?? '',
    appId: dotenv.env["iosappId"] ?? '',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    iosBundleId: 'com.example.wosapp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env["macosapiKey"] ?? '',
    appId: dotenv.env["macosappId"] ?? '',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    iosBundleId: 'com.example.wosapp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env["windowsapiKey"] ?? '',
    appId: dotenv.env["windowsappId"] ?? '',
    messagingSenderId: '1073439472535',
    projectId: 'wosapp-a2214',
    authDomain: 'wosapp-a2214.firebaseapp.com',
    storageBucket: 'wosapp-a2214.firebasestorage.app',
    measurementId: 'G-DMF4HG0FLW',
  );
}
